binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine" # *
color = "Auto"
combine_control_expr = true
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2024"
empty_item_single_line = true
enum_discrim_align_threshold = 40 # sync with `struct_field_align_threshold`
error_on_line_overflow = true
error_on_unformatted = false
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false # *
format_code_in_doc_comments = true
doc_comment_code_block_width = 60
format_generated_files = false
generated_marker_line_search_limit = 1
format_macro_matchers = true
format_macro_bodies = true
skip_macro_invocations = []
format_strings = false
hard_tabs = true
hex_literal_case = "Upper"
show_parse_errors = true
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = false
match_arm_leading_pipes = "Never"

max_width = 250

merge_derives = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 10 # *
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0 # sync with `enum_discrim_align_threshold`
struct_lit_single_line = true
style_edition = "2024"
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = true
wrap_comments = false
