group_and_type!(YearByYear {
    age
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(Season {
    age
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
    passedBall
    pickoffAttempts
});
group_and_type!(Career {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
    passedBall
});
group_and_type!(GameLog {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(LastXGames {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(ByDateRange {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(ByDateRangeAdvanced {
    battersFaced
    stolenBases
    caughtStealing
    wildPitches
    pickoffs
});
group_and_type!(ByMonth {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(ByDayOfWeek {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(HomeAndAway {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
group_and_type!(WinLoss {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});

