group_and_type!(YearByYear {
	"age" => age,
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(Season {
	"age" => age,
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(Career {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(GameLog {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(LastXGames {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(ByDateRange {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(ByDateRangeAdvanced {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	// "position" => position,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(ByMonth {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(ByDayOfWeek {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(HomeAndAway {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(WinLoss {
	"gamesPlayed" => games_played,
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	"innings" => innings,
	"games" => games,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	"doublePlays" => double_plays,
	"triplePlays" => triple_plays,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"catchersInterference" => catchers_interference,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"wildPitches" => wild_pitches,
	"throwingErrors" => throwing_errors,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
group_and_type!(SimplifiedGameLog {
	"gamesStarted" => games_started,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"caughtStealing" => caught_stealing,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"stolenBases" => stolen_bases,
	"assists" => assists,
	"putOuts" => putouts,
	"errors" => errors,
	"chances" => chances,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"passedBall" => passed_balls,
	#[cfg_attr(test, serde(default = "crate::stats::raw::default_stat"))]
	"pickoffs" => pickoffs,
});
