kind!(YearByYear {
    age
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
kind!(Season {
    age
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
    passedBall
    pickoffAttempts
});
kind!(Career {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
    passedBall
});
kind!(GameLog {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
kind!(LastXGames {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ByDateRange {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ByDateRangeAdvanced {
    battersFaced
    stolenBases
    caughtStealing
    wildPitches
    pickoffs
});
kind!(ByMonth {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ByDayOfWeek {
    gamesPlayed
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    earnedRuns
    battersFaced
    gamesPitched
    hitBatsmen
    wildPitches
    pickoffs
    totalBases
    catchersInterference
    sacBunts
    sacFlies
});
kind!()
