kind!(Projected {
    gamesPlayed
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    plateAppearances
    totalBases
    rbi
    sacBunts
    sacFlies
    woba
    wRaa
    wRc
    wRcPlus
    rar
    war
    batting
    fielding
    baseRunning
    positional
    replacement
    spd
    ubr
    wSb
});
kind!(YearByYear {
    age
    gamesPlayed
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(YearByYearAdvanced {
    age
    plateAppearances
    totalBases
    leftOnBase
    sacBunts
    sacFlies
    extraBaseHits
    hitByPitch
    gidp
    gidpOpp
    numberOfPitches
    reachedOnError
    walkOffs
    flyOuts
    totalSwings
    swingAndMisses
    ballsInPlay
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(Season {
    age
    gamesPlayed
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(Career {
    gamesPlayed
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(SeasonAdvanced {
    age
    plateAppearances
    totalBases
    leftOnBase
    sacBunts
    sacFlies
    extraBaseHits
    hitByPitch
    gidp
    gidpOpp
    numberOfPitches
    reachedOnError
    walkOffs
    flyOuts
    totalSwings
    swingAndMisses
    ballsInPlay
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(CareerAdvanced {
    plateAppearances
    totalBases
    leftOnBase
    sacBunts
    sacFlies
    extraBaseHits
    hitByPitch
    gidp
    gidpOpp
    numberOfPitches
    reachedOnError
    walkOffs
    flyOuts
    totalSwings
    swingAndMisses
    ballsInPlay
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(GameLog {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(ExpectedStatistics {
    avg
    slg
    woba
    wobaCon
});
kind!(Sabermetrics {
    woba
    wRaa
    wRc
    wRcPlus
    rar
    war
    batting
    fielding
    baseRunning
    positional
    wLeague
    replacement
    spd
    ubr
    wGdp
    wSb
});
kind!(LastXGames {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(ByDateRange {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(ByDateRangeAdvanced {
    plateAppearances
    totalBases
    leftOnBase
    sacBunts
    sacFlies
    extraBaseHits
    hitByPitch
    gidp
    gidpOpp
    numberOfPitches
    reachedOnError
    walkOffs
    flyOuts
    totalSwings
    swingAndMisses
    ballsInPlay
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(ByMonth {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(ByDayOfWeek {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(HomeAndAway {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(WinLoss {
    gamesPlayed
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(Rankings {
    gamesPlayed
    runs
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    avg
    atBats
    obp
    slg
    ops
    caughtStealing
    stolenBases
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    catchersInterference
});
kind!(RankingsByYear {
    gamesPlayed
    runs
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    avg
    atBats
    obp
    slg
    ops
    caughtStealing
    stolenBases
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    catchersInterference
});
kind!(StatSplits {
    gamesPlayed
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    groundIntoTriplePlay
    numberOfPitches
    plateAppearances
    totalBases
    rbi
    leftOnBase
    sacBunts
    sacFlies
    catchersInterference
});
kind!(StatSplitsAdvanced {
    plateAppearances
    totalBases
    leftOnBase
    sacBunts
    sacFlies
    extraBaseHits
    hitByPitch
    gidp
    gidpOpp
    numberOfPitches
    reachedOnError
    walkOffs
});
