kind!(Projected {
    gamesPlayed
    gamesStarted
    runs
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    avg
    inningsPitched
    wins
    losses
    saves
    holds
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    hitBatsmen
    fip
    ra9War
    rar
    war
    lobWins
    bipWins
    fdpWins
    qualityStarts
});
kind!(YearByYear {
    age
    gamesPlayed
    gamesStarted
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(YearByYearAdvanced {
    age
    battersFaced
    inheritedRunners
    inheritedRunnersScored
    bequeathedRunners
    bequeathedRunnersScored
    stolenBases
    caughtStealing
    qualityStarts
    gamesFinished
    doubles
    triples
    gidp
    gidpOpp
    wildPitches
    balks
    pickoffs
    totalSwings
    swingAndMisses
    buntsFailed
    buntsMissedTipped
    ballsInPlay
    runSupport
    flyOuts
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(Season {
    age
    gamesPlayed
    gamesStarted
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(Career {
    gamesPlayed
    gamesStarted
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(SeasonAdvanced {
    age
    battersFaced
    inheritedRunners
    inheritedRunnersScored
    bequeathedRunners
    bequeathedRunnersScored
    stolenBases
    caughtStealing
    qualityStarts
    gamesFinished
    doubles
    triples
    gidp
    gidpOpp
    wildPitches
    balks
    pickoffs
    totalSwings
    swingAndMisses
    buntsFailed
    buntsMissedTipped
    ballsInPlay
    runSupport
    flyOuts
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(CareerAdvanced {
    battersFaced
    inheritedRunners
    inheritedRunnersScored
    bequeathedRunners
    bequeathedRunnersScored
    stolenBases
    caughtStealing
    qualityStarts
    gamesFinished
    doubles
    triples
    gidp
    gidpOpp
    wildPitches
    balks
    pickoffs
    totalSwings
    swingAndMisses
    buntsFailed
    buntsMissedTipped
    ballsInPlay
    runSupport
    flyOuts
    popOuts
    lineOuts
    groundOuts
    flyHits
    popHits
    lineHits
    groundHits
});
kind!(GameLog {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ExpectedStatistics {
    avg
    slg
    woba
    wobaCon
});
kind!(Sabermetrics {
    fip
    xfip
    fipMinus
    ra9War
    rar
    war
    sd
    md
    pli
    inli
    gmli
    exli
    eraMinus
});
kind!(LastXGames {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ByDateRange {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ByDateRangeAdvanced {
    battersFaced
    stolenBases
    caughtStealing
    gamesFinished
    gidp
    wildPitches
    balks
    pickoffs
    groundOuts
});
kind!(ByMonth {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(ByDayOfWeek {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(HomeAndAway {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(WinLoss {
    gamesPlayed
    gamesStarted
    flyOuts
    groundOuts
    airOuts
    runs
    doubles
    triples
    homeRuns
    strikeOuts
    baseOnBalls
    intentionalWalks
    hits
    hitByPitch
    atBats
    caughtStealing
    stolenBases
    groundIntoDoublePlay
    numberOfPitches
    inningsPitched
    wins
    losses
    saves
    saveOpportunities
    holds
    blownSaves
    earnedRuns
    battersFaced
    outs
    gamesPitched
    completeGames
    shutouts
    strikes
    hitBatsmen
    balks
    wildPitches
    pickoffs
    totalBases
    gamesFinished
    inheritedRunners
    inheritedRunnersScored
    catchersInterference
    sacBunts
    sacFlies
});
kind!(Rankings {
    wildPitches
});
kind!(RankingsByYear {
    wildPitches
});
